# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://git-inner.cpgroupcloud.com/root/ModuleSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'LBPayDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LBPayDemo
  pod 'LBPay', :path => '../'
  
  pod 'ZDBaseModule'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end

end
